version: '3.8'
services:

  php-apache:
    build:
      context: .
      target: php-apache
    image: local/benchmarks/php-apache:latest
    ports: [8000:80]

  php-fpm:
    build:
      context: .
      target: php-fpm
    image: local/benchmarks/php-fpm:latest
  php-fpm-nginx:
    image: nginx:1-alpine
    volumes: [./nginx.conf:/etc/nginx/conf.d/default.conf:ro]
    depends_on: [php-fpm]
    ports: [8000:80]

  php-octane:
    build:
      context: .
      target: php-octane
    image: local/benchmarks/php-octane:latest
    ports: [8000:8000]
