version: '3.8'
services:

  php-apache:
    build:
      context: .
      target: php-apache
    image: local/benchmarks/php-apache:latest
    ports: [8000:80]

  php-fpm:
    build:
      context: .
      target: php-fpm
    image: local/benchmarks/php-fpm:latest
  php-fpm-nginx:
    image: nginx:1-alpine
    volumes: [./files/nginx.conf:/etc/nginx/conf.d/default.conf:ro]
    depends_on: [php-fpm]
    ports: [8000:80]

  php-fpm-nginx-custom:
    build:
      context: .
      target: php-fpm-nginx-custom
    image: local/benchmarks/php-fpm-nginx-custom:latest
    ports: [8000:80]
    extra_hosts: [php-fpm:127.0.0.1]

  php-octane:
    build:
      context: .
      target: php-octane
    image: local/benchmarks/php-octane:latest
    ports: [8000:8000]

  php-octane-alpine:
    build:
      context: .
      target: php-octane-alpine
    image: local/benchmarks/php-octane-alpine:latest
    ports: [8000:8000]
