name: benchmark
on: push
jobs:
  run-benchmarks:
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: true
      PYTHONUNBUFFERED: true
    steps:
      - uses: actions/checkout@v2
      - name: Run benchmarks
        run: python run.py
